apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: armd-postgres
  namespace: default

spec:

   replicas: 3
   image: postgres:14.1

   database:
      size: 10Gi

   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: postgres-pswd
              key: superUserPassword

      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: postgres-pswd
              key: replicationUserPassword