apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-ingress
spec:
  rules:
  - http:
      paths:
      - path: /.*
        pathType: Prefix
        backend:
          service:
            name: armd-client-service
            port:
              number: 80
